version: '3.7'

services:
  server:
    build:
      context: ..  # context is parent to access ../shared/entities from Dockerfile
      dockerfile: server/app/Dockerfile
    command: uvicorn faq_server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
